# Generated by Django 4.2.7 on 2023-12-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование дисциплины', max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО', max_length=255)),
                ('bdate', models.DateField(help_text='Дата рождения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shapp.group')),
            ],
        ),
    ]
