# Generated by Django 4.2.7 on 2023-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapp', '0002_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ManyToManyField(to='shapp.group'),
        ),
    ]
